import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import React from 'react'
// import ReactDOM from 'react-dom';
import { store } from '../redux/configureStore';
// import { Provider } from 'react-redux';
import { HomeScreen } from './homeScreen';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

//ReactDOM.render(<Provider store={store}><HomeScreen /></Provider>, document.getElementById('root'));

// render(
//   <Provider store={store}>
//     <HomeScreen />
//   </Provider>
//   //document.getElementById('root')
// )


// ReactDOM.render(
//   <Provider store={store}>
//      <HomeScreen />
//   </Provider>,
//   document.getElementById('root')
// );

export default function Home() {
  return (
    <>
        {/* <Provider store={store}> */}
            <h1 ><Link href="Exercise1/flexDemo">Flex Page</Link></h1>
            <h1 ><Link href="Exercise1/ResponsiveDemo">Responsive Page</Link></h1>
            <h1> <Link href="LoginScreen/loginScreen">Login Page</Link></h1>
          {/* <HomeScreen /> */}
        {/* </Provider> */}
        {/* <h1 className = "title"><Link href="Exercise1/flexDemo">Flex Page</Link></h1>
        <h1 className = "title"><Link href="Exercise1/ResponsiveDemo">Responsive Page</Link></h1>
        <h1> <Link href="LoginScreen/loginScreen">Login Page</Link></h1>
        <div class="space-y-4">
          <div class="w-96 bg-white shadow rounded">
              w-96
          </div>
          <div class="w-80 bg-white shadow rounded">
              w-80
          </div>
          <div class="w-72 bg-greenMaster-100  shadow rounded">
              w-72
          </div>
          <div class="w-64 bg-greenMaster-300  shadow rounded">
              w-64
          </div>
          <div class="w-60 bg-greenMaster-500 shadow rounded">
              w-60
          </div>
          <div class="w-56 bg-greenMaster-900 shadow rounded">
              w-56
          </div>
          <div class="w-52 bg-white shadow rounded">
              w-52
          </div>
          <div class="w-48 bg-white shadow rounded">
              w-48
          </div>
        </div> */}
        {/* <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <div className={styles.description}>
            <p>
              Get started by editing&nbsp;
              <code className={styles.code}>pages/index.js</code>
            </p>
            <div>
              <a
                href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
              >
                By{' '}
                <Image
                  src="/vercel.svg"
                  alt="Vercel Logo"
                  className={styles.vercelLogo}
                  width={100}
                  height={24}
                  priority
                />
              </a>
            </div>
          </div>

          <div className={styles.center}>
            <Image
              className={styles.logo}
              src="/next.svg"
              alt="Next.js Logo"
              width={180}
              height={37}
              priority
            />
            <div className={styles.thirteen}>
              <Image
                src="/thirteen.svg"
                alt="13"
                width={40}
                height={31}
                priority
              />
            </div>
          </div>

          <div className={styles.grid}>
            <a
              href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2 className={inter.className}>
                Docs <span>-&gt;</span>
              </h2>
              <p className={inter.className}>
                Find in-depth information about Next.js features and&nbsp;API.
              </p>
            </a>

            <a
              href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2 className={inter.className}>
                Learn <span>-&gt;</span>
              </h2>
              <p className={inter.className}>
                Learn about Next.js in an interactive course with&nbsp;quizzes!
              </p>
            </a>

            <a
              href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2 className={inter.className}>
                Templates <span>-&gt;</span>
              </h2>
              <p className={inter.className}>
                Discover and deploy boilerplate example Next.js&nbsp;projects.
              </p>
            </a>

            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2 className={inter.className}>
                Deploy <span>-&gt;</span>
              </h2>
              <p className={inter.className}>
                Instantly deploy your Next.js site to a shareable URL
                with&nbsp;Vercel.
              </p>
            </a>
          </div>
        </main> */}
        
    </>
  )
}
